"use strict";
/**
 * tsc app.ts --target ES2020
 */
// ======== Update Begin ======= //
const currentName = `<a href="https://1592063346.github.io/learn/5thxwb-main" class="link">第五届曦望杯</a>`;
const currentForbiddenDesc = `<u>卡通</u>、<u>杀手级调整曲</u>`;
// const currentForbiddenDesc = '无追加字段限制';
// generated by forbiddenDictGen.py
const forbiddenCardList = {
    // 卡通
    5832914: ["卡通手提箱", 0],
    6958551: ["影子卡通", 0],
    7171149: ["卡通古代的机械巨人", 0],
    7293697: ["完美世界 卡通世界", 0],
    15259703: ["卡通世界", 0],
    15259704: ["卡通世界", 0],
    15270885: ["卡通哥布林突击部队", 0],
    16392422: ["卡通假面魔道士", 0],
    21296502: ["卡通黑魔术师", 0],
    27699122: ["卡通翻阅", 0],
    28112535: ["卡通左轮手枪龙", 0],
    28711704: ["卡通混沌战士", 0],
    38369349: ["卡通蛋龙", 0],
    42386471: ["卡通双生精灵", 0],
    43175858: ["卡通王国", 0],
    43509019: ["卡通防御", 0],
    53094821: ["卡通恐怖", 0],
    53183600: ["青眼卡通龙", 0],
    53183601: ["青眼卡通龙", 0],
    59383041: ["卡通鳄鱼", 0],
    61190918: ["卡通破坏之剑士", 0],
    64116319: ["卡通鹰身女郎", 0],
    65458948: ["卡通人鱼", 0],
    70560957: ["卡通倒带", 0],
    79447365: ["卡通面具", 0],
    79875176: ["卡通加农炮兵", 0],
    89997728: ["卡通目录", 0],
    91500017: ["卡通书签", 0],
    91842653: ["卡通恶魔", 0],
    // 杀手级调整曲
    14442329: ["点唱机酒吧“杀手级调整曲”", 0],
    15665977: ["杀手级调整曲·红印鉴唱片师", 0],
    16387555: ["杀手级调整曲·提示员", 0],
    16509007: ["杀手级调整曲·混音手", 0],
    17209452: ["杀手级调整曲·旋钮手", 0],
    39576656: ["杀手级调整曲·噼啪削波手", 0],
    40847034: ["杀手级调整曲播放列表", 0],
    41069676: ["杀手级调整曲响度战争", 0],
    42781164: ["杀手级调整曲·音轨制作人", 0],
    43904702: ["杀手级调整曲·削波手", 0],
    65961304: ["杀手级调整曲 B2B", 0],
    78058681: ["杀手级调整曲同调", 0],
    88170262: ["杀手级调整曲·再混音手", 0],
    89392810: ["杀手级调整曲·唱片师", 0],
};
// ======== Update End ======= //
class DeckChecker {
    constructor(containerId) {
        this.state = 'idle';
        this.source = null;
        const container = document.getElementById(containerId);
        if (!container) {
            throw new Error(`Container Not Found.`);
        }
        this.elements = this.buildUI(container);
        this.bindEvents();
        console.log('Init Ok.');
    }
    buildUI(container) {
        const card = document.createElement('div');
        card.className = 'card';
        // ----- Title -----
        const title = document.createElement('div');
        title.className = 'card-title';
        title.innerHTML = `<span>曦望杯卡组自查</span>`;
        // ----- Desc -----
        const description = document.createElement('p');
        description.className = 'description';
        description.innerHTML = `
            这一工具将帮助你检查卡组是否符合目前曦望杯比赛的<font color=purple>字段追加限制</font>要求。<br />
        `;
        description.innerHTML += '目前适用比赛：' + currentName + `<br />`;
        description.innerHTML += '追加限制字段：' + currentForbiddenDesc + `<br />`;
        // ----- Input (text) -----
        const inputGroup = document.createElement('div');
        inputGroup.className = 'input-group';
        const inputRow = document.createElement('div');
        inputRow.className = 'input-row';
        const input = document.createElement('textarea');
        // input.type = 'text';
        input.id = 'textInput';
        input.placeholder = '粘贴卡组 .ydk 文本到此处';
        input.autocomplete = 'off';
        input.spellcheck = false;
        input.setAttribute('aria-label', '输入要检测的文字');
        input.style.resize = 'none';
        const button = document.createElement('button');
        button.className = 'btn-submit';
        button.id = 'submitBtn';
        button.type = 'button';
        button.textContent = '检查';
        inputRow.appendChild(input);
        inputRow.appendChild(button);
        inputGroup.appendChild(inputRow);
        // ----- Input (.ydk file) -----
        const fileRow = document.createElement('div');
        fileRow.className = 'input-row file-row'; // 使用 file-row 提供 margin-top
        const fileLabel = document.createElement('span');
        fileLabel.textContent = '或上传 .ydk 文件：';
        fileLabel.className = 'file-label';
        const fileInput = document.createElement('input');
        fileInput.type = 'file';
        fileInput.id = 'fileInput';
        fileInput.accept = '.ydk';
        fileInput.className = 'file-input';
        fileInput.setAttribute('aria-label', '上传 .ydk 文件');
        fileRow.appendChild(fileLabel);
        fileRow.appendChild(fileInput);
        inputGroup.appendChild(fileRow);
        // ----- Result -----
        const resultArea = document.createElement('div');
        resultArea.className = 'result-area';
        resultArea.id = 'resultArea';
        resultArea.setAttribute('aria-live', 'polite');
        const resultText = document.createElement('span');
        resultText.className = 'result-text placeholder';
        resultText.id = 'resultText';
        resultText.textContent = '等待粘贴卡组码或上传文件…';
        resultArea.appendChild(resultText);
        // ----- Footnote -----
        const footer = document.createElement('div');
        footer.className = 'footer-note';
        footer.style.textAlign = 'left';
        footer.innerHTML = '注意：该工具仅能检查你的卡组是否符合目前曦望杯比赛的字段追加限制要求，'
            + '不会检查卡组是否符合目前曦望杯比赛适用的原本禁限卡表，'
            + '也不会检查每一张卡片是否合法。';
        card.appendChild(title);
        card.appendChild(description);
        card.appendChild(inputGroup);
        card.appendChild(resultArea);
        card.appendChild(footer);
        container.innerHTML = '';
        container.appendChild(card);
        return { input, button, fileInput, resultArea, resultText };
    }
    check(text) {
        const lines = text.trim().split(/\r?\n/);
        let i = 0;
        const numbers = [];
        // #created by ...
        if (i >= lines.length || !lines[i].trim().startsWith("#created by ")) {
            return DeckChecker.CHECK_FORMAT_ERROR;
        }
        i++;
        // #main
        if (i >= lines.length || lines[i].trim() !== "#main") {
            return DeckChecker.CHECK_FORMAT_ERROR;
        }
        i++;
        let mainCount = 0;
        while (i < lines.length && lines[i].trim() !== "#extra") {
            const numLine = lines[i].trim();
            if (numLine === "" || !/^\d+$/.test(numLine)) {
                return DeckChecker.CHECK_FORMAT_ERROR;
            }
            const num = Number(numLine);
            if (num < 0 || num > 99999999) {
                return DeckChecker.CHECK_FORMAT_ERROR;
            }
            numbers.push(num);
            mainCount++;
            i++;
        }
        if (mainCount < 40 || mainCount > 60) {
            return {
                code: DeckChecker.CODE_LIMIT_ERROR,
                message: `主卡组卡片数量不满足要求！`
            };
        }
        // #extra
        if (i >= lines.length || lines[i].trim() !== "#extra") {
            return DeckChecker.CHECK_FORMAT_ERROR;
        }
        i++;
        let extraCount = 0;
        while (i < lines.length && lines[i].trim() !== "!side") {
            const numLine = lines[i].trim();
            if (numLine === "" || !/^\d+$/.test(numLine)) {
                return DeckChecker.CHECK_FORMAT_ERROR;
            }
            const num = Number(numLine);
            if (num < 0 || num > 99999999) {
                return DeckChecker.CHECK_FORMAT_ERROR;
            }
            numbers.push(num);
            extraCount++;
            i++;
        }
        if (extraCount > 15) {
            return {
                code: DeckChecker.CODE_LIMIT_ERROR,
                message: `额外卡组卡片数量超过限制！`
            };
        }
        // !side
        if (i >= lines.length || lines[i].trim() !== "!side") {
            return DeckChecker.CHECK_FORMAT_ERROR;
        }
        i++;
        let sideCount = 0;
        while (i < lines.length) {
            const numLine = lines[i].trim();
            if (numLine === "" || !/^\d+$/.test(numLine)) {
                return DeckChecker.CHECK_FORMAT_ERROR;
            }
            const num = Number(numLine);
            if (num < 0 || num > 99999999) {
                return DeckChecker.CHECK_FORMAT_ERROR;
            }
            numbers.push(num);
            sideCount++;
            i++;
        }
        if (sideCount > 15) {
            return {
                code: DeckChecker.CODE_LIMIT_ERROR,
                message: `副卡组卡片数量超过限制！`
            };
        }
        const countMap = new Map();
        for (const num of numbers) {
            countMap.set(num, (countMap.get(num) || 0) + 1);
        }
        for (const [num, count] of countMap) {
            if (count > 3) {
                return {
                    code: DeckChecker.CODE_LIMIT_ERROR,
                    message: `存在卡片投入数量大于 3！`
                };
            }
            if (num in forbiddenCardList) {
                const limit = forbiddenCardList[num][1];
                if (count > limit) {
                    return {
                        code: DeckChecker.CODE_LIMIT_ERROR,
                        message: `卡组不满足追加限制要求：投入了超过限制数量的「${forbiddenCardList[num][0]}」。`
                    };
                }
            }
        }
        return DeckChecker.CHECK_SUCCESS;
    }
    handleSubmit() {
        const raw = this.elements.input.value;
        const trimmed = raw.trim();
        if (trimmed.length === 0) {
            this.setState('idle', '等待粘贴卡组码或上传文件…', null);
            return;
        }
        const result = this.check(trimmed);
        this.source = 'input';
        if (result.code == 0) {
            this.setState('correct', result.message, 'input');
        }
        else {
            this.setState('error', result.message, 'input');
        }
    }
    handleFileUpload(file) {
        if (!file.name.toLowerCase().endsWith('.ydk')) {
            this.setState('error', `请上传 .ydk 格式的文件！`, null);
            return;
        }
        const reader = new FileReader();
        reader.onload = (e) => {
            try {
                const content = e.target?.result;
                if (!content || content.trim().length === 0) {
                    this.setState('error', `文件内容为空！`, null);
                    return;
                }
                const result = this.check(content);
                this.source = 'file';
                if (result.code == 0) {
                    this.setState('correct', result.message, 'input');
                }
                else {
                    this.setState('error', result.message, 'input');
                }
            }
            catch (err) {
                this.setState('error', `读取文件失败: ${err}`, null);
            }
        };
        reader.onerror = () => {
            this.setState('error', `文件读取出错！`, null);
        };
        reader.readAsText(file, 'UTF-8');
    }
    resetIfEmpty() {
        const raw = this.elements.input.value;
        const fileInput = this.elements.fileInput;
        if (raw.trim().length === 0 && fileInput.files?.length === 0 && this.state !== 'idle') {
            this.setState('idle', '等待粘贴卡组码或上传文件…', null);
        }
    }
    setState(state, message, source) {
        this.state = state;
        this.source = source;
        const { resultArea, resultText } = this.elements;
        resultArea.classList.remove('correct', 'error');
        resultText.classList.remove('correct', 'error', 'placeholder');
        switch (state) {
            case 'idle':
                resultText.classList.add('placeholder');
                resultText.textContent = message;
                break;
            case 'correct':
                resultArea.classList.add('correct');
                resultText.classList.add('correct');
                // const srcLabel = source === 'file' ? ' (文件)' : source === 'input' ? ' (输入)' : '';
                // resultText.textContent = message + srcLabel;
                resultText.textContent = message;
                break;
            case 'error':
                resultArea.classList.add('error');
                resultText.classList.add('error');
                // const errLabel = source === 'file' ? ' (文件)' : source === 'input' ? ' (输入)' : '';
                // resultText.textContent = message + errLabel;
                resultText.textContent = message;
                break;
        }
    }
    bindEvents() {
        const { input, button, fileInput } = this.elements;
        button.addEventListener('click', () => {
            this.handleSubmit();
        });
        // input.addEventListener('keydown', (e: KeyboardEvent) => {
        //     if (e.key === 'Enter') {
        //         e.preventDefault();
        //         this.handleSubmit();
        //     }
        // });
        input.addEventListener('input', () => {
            this.resetIfEmpty();
        });
        input.addEventListener('blur', () => {
            this.resetIfEmpty();
        });
        fileInput.addEventListener('change', (e) => {
            const target = e.target;
            const file = target.files?.[0];
            if (file) {
                this.handleFileUpload(file);
            }
            else {
                this.resetIfEmpty();
            }
        });
    }
}
DeckChecker.CODE_SUCCESS = 0;
DeckChecker.CODE_FORMAT_ERROR = 1;
DeckChecker.CODE_LIMIT_ERROR = 2;
DeckChecker.CODE_DEBUG = 3;
DeckChecker.CHECK_SUCCESS = { code: DeckChecker.CODE_SUCCESS, message: "卡组检查通过。" };
DeckChecker.CHECK_FORMAT_ERROR = { code: DeckChecker.CODE_FORMAT_ERROR, message: "卡组码或文件格式错误！" };
DeckChecker.CHECK_DEBUG = { code: DeckChecker.CODE_DEBUG, message: "" };
document.addEventListener('DOMContentLoaded', () => {
    try {
        const checker = new DeckChecker('app');
        window.__checker = checker;
    }
    catch (err) {
        console.error('Error:', err);
    }
});
